name: "Connect Issue to PR"
on: 
  pull_request:
      types: [opened]
      
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Post PR Create Action
        uses: Zejnilovic/post-pr-create-action@v1.3
        with:
          ZENHUB_TOKEN: ${{ secrets.ZENHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
